services:
  chatserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chatserver
    restart: always
    depends_on:
      - postgresql
    networks:
      - private
      - public
    ports: 
      - "3000:3000"  # Porta do servidor Express
      - "3001:3001"  # Porta do servidor WebSocket

  postgresql:
    image: postgres:latest
    restart: always
    container_name: dbserver
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - private
    ports:
      - "5432:5432"
    volumes:
      - postgresv:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadminserver
    ports: 
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: brendo.dkry@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - private

volumes:
  postgresv: 

networks:
  private: 
  public: